name: Deploy to Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create deployment package
        run: |
          mkdir package
          pip install numpy --platform manylinux2014_aarch64 --only-binary=:all: --target ./package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .
          cd ..
          rm -rf package

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda_function.zip

      - name: Remove deployment package
        run: |
          rm -rf lambda_function.zip

      - name: Verify deployment
        run: |
          RESPONSE=$(aws lambda get-function --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }})
          echo "Lambda function updated: $RESPONSE"
          echo "LAMBDA_UPDATE_STATUS=success" >> $GITHUB_ENV
